// FontAwesome icon library setup.
//
// We register ONLY the icons actually referenced by string name across the app
// (e.g. <FontAwesomeIcon icon="cog" />). Importing the whole `fas`/`far`/`fab`
// sets used to pull ~1MB of icon data into the initial bundle; this curated list
// keeps that down to a few dozen icons. Legacy string names (cog, edit, times,
// sync, ...) still resolve because each v7 icon definition carries its old names
// in its built-in aliases.
//
// If an icon renders as an empty box, add its export here. Components that import
// icon objects directly (e.g. `import { faTrophy } from '.../free-solid-svg-icons'`)
// do NOT need to be listed — only string-name / ['prefix', 'name'] usages do.
import { library } from '@fortawesome/fontawesome-svg-core';
import { faDiscord, faGithub } from '@fortawesome/free-brands-svg-icons';
import { faFlag } from '@fortawesome/free-regular-svg-icons';
import {
  faArrowCircleDown,
  faArrowCircleUp,
  faArrowRight,
  faBan,
  faBinoculars,
  faCheck,
  faCheckCircle,
  faChessKnight,
  faChevronDown,
  faChevronUp,
  faCircle,
  faClock,
  faCog,
  faCommentAlt,
  faCommentSlash,
  faCopy,
  faEdit,
  faEllipsisV,
  faExchangeAlt,
  faExclamationCircle,
  faExpand,
  faEye,
  faEyeSlash,
  faFlagCheckered,
  faHandshake,
  faInfo,
  faInfoCircle,
  faKey,
  faLaptopCode,
  faLayerGroup,
  faLink,
  faLock,
  faMoon,
  faPause,
  faPen,
  faPlay,
  faPlayCircle,
  faQuestionCircle,
  faRedo,
  faRobot,
  faRss,
  faSearch,
  faSignal,
  faSitemap,
  faSortAmountUp,
  faSpinner,
  faStop,
  faStopwatch,
  faSun,
  faSync,
  faTasks,
  faTimes,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTrophy,
  faUnlock,
  faUser,
  faUserMinus,
  faUserPlus,
  faUsers,
  faVideo,
  faVolumeMute,
  faWineBottle,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  // solid
  faArrowCircleDown,
  faArrowCircleUp,
  faArrowRight,
  faBan,
  faBinoculars,
  faCheck,
  faCheckCircle,
  faChessKnight,
  faChevronDown,
  faChevronUp,
  faCircle,
  faClock,
  faCog,
  faCommentAlt,
  faCommentSlash,
  faCopy,
  faEdit,
  faEllipsisV,
  faExchangeAlt,
  faExclamationCircle,
  faExpand,
  faEye,
  faEyeSlash,
  faFlagCheckered,
  faHandshake,
  faInfo,
  faInfoCircle,
  faKey,
  faLaptopCode,
  faLayerGroup,
  faLink,
  faLock,
  faMoon,
  faPause,
  faPen,
  faPlay,
  faPlayCircle,
  faQuestionCircle,
  faRedo,
  faRobot,
  faRss,
  faSearch,
  faSignal,
  faSitemap,
  faSortAmountUp,
  faSpinner,
  faStop,
  faStopwatch,
  faSun,
  faSync,
  faTasks,
  faTimes,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTrophy,
  faUnlock,
  faUser,
  faUserMinus,
  faUserPlus,
  faUsers,
  faVideo,
  faVolumeMute,
  faWineBottle,
  // regular
  faFlag,
  // brands
  faGithub,
  faDiscord,
);
