ARG RUNNER_IMAGE=ghcr.io/hexlet-codebattle/runner-zig:latest
ARG ALPINE_TAG=3.23
ARG TARGETPLATFORM

FROM --platform=$TARGETPLATFORM ${RUNNER_IMAGE} AS runner
FROM --platform=$TARGETPLATFORM alpine:${ALPINE_TAG}

# edge repos for Dart & ICU
RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
  echo "@edgecommunity http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
  echo "@edgemain http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
  apk add --update --no-cache make ca-certificates curl icu-libs@edgemain icu-data-full@edgecommunity dart@edge

# app user
RUN addgroup -S app -g 10001 \
  && adduser -S -D -H -h /home/app -s /sbin/nologin -G app -u 10001 app \
  && mkdir -p /home/app/.dart-tool /usr/src/app \
  && chown -R app:app /home/app /usr/src/app

WORKDIR /usr/src/app

ENV HOME=/home/app

USER app

COPY pubspec.yaml .
COPY pubspec.lock .
RUN dart pub get

COPY lib lib
COPY Makefile .

RUN dart pub get --offline

EXPOSE 8000
COPY --from=runner /app/codebattle_runner /runner/codebattle_runner
ENTRYPOINT ["/runner/codebattle_runner"]
