[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "check"
path = "check/checker.rs"

[dependencies]
libc = "0.2.153"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.7.0"
