ARG RUNNER_IMAGE=ghcr.io/hexlet-codebattle/runner-zig:latest
ARG RUST_TAG=1.93.0-alpine3.23
ARG TARGETPLATFORM

FROM --platform=$TARGETPLATFORM ${RUNNER_IMAGE} AS runner
FROM --platform=$TARGETPLATFORM rust:${RUST_TAG}

RUN apk add --no-cache make libc-dev

RUN addgroup -S app -g 10001 \
  && adduser -S -D -H -h /nonexistent -s /sbin/nologin -G app -u 10001 app

WORKDIR /usr/src/app

COPY Cargo.toml .
COPY check ./check
COPY Makefile .

RUN cargo build
RUN chown -R app:app /usr/src/app

USER app

EXPOSE 4040
COPY --from=runner /app/codebattle_runner /runner/codebattle_runner
ENTRYPOINT ["/runner/codebattle_runner"]
