
defmodule A do
  def a do
[%{struct: Codebattle.Game.Player,
  achievements: [],
  check_result: %Codebattle.CodeCheck.CheckResult{asserts: [], asserts_count: 0, output: "", result: "{\"status\": \"info\"}", status: "initial", success_count: 0},
  creator: true,
  editor_lang: "js",
  editor_text: "const _ = require(\"lodash\");\nconst R = require(\"rambda\");\n\nconst solution = (a, b) => {\n\treturn 0;\n};\n\nmodule.exports = solution;",
  id: 4207778,
  is_bot: false,
  lang: "js",
  name: "User 0",
  rank: 5432,
  rating: 1001,
  rating_diff: 0,
  result: "gave_up",
  task: %Codebattle.Task{__meta__: "tasks",
    asserts: [%{"arguments" => [1, 1], "expected" => 2}, %{"arguments" => [2, 1], "expected" => 3}, %{"arguments" => [3, 2], "expected" => 5}],
    count: nil,
    creator_id: nil,
    description_en: "test sum",
    description_ru: "проверка суммы",
    disabled: false,
    examples: "asfd",
    id: 3327,
    input_signature: [%{"argument-name" => "a",
      "type" => %{"name" => "integer"}},
      %{"argument-name" => "b",
        "type" => %{"name" => "integer"}}],
    inserted_at: ~N[2021-12-07 13:00:23],
    level: "easy",
    name: "3A03",
    origin: "user",
    output_signature: %{"type" => %{"name" => "integer"}},
    state: "active",
    tags: [],
    updated_at: ~N[2021-12-07 13:00:23],
    visibility: "public"}},
    %{__struct__: Codebattle.Game.Player,
      achievements: [],
      check_result: %Codebattle.CodeCheck.CheckResult{asserts: [],
        asserts_count: 0,
        output: "",
        result: "{\"status\": \"info\"}",
        status: "initial",
        success_count: 0},
      creator: false,
      editor_lang: "js",
      editor_text: "const _ = require(\"lodash\");\nconst R = require(\"rambda\");\n\nconst solution = (a,
        b) => {\n\treturn 0;\n};\n\nmodule.exports = solution;",
      id: 7881260,
      is_bot: false,
      lang: "js",
      name: "User 2",
      rank: 5432,
      rating: 1002,

      rating_diff: 0,
      result: "won",
      task: %Codebattle.Task{__meta__: "tasks",
        asserts: [%{"arguments" => [1,
          1],
          "expected" => 2},
          %{"arguments" => [2,
            1],
            "expected" => 3},

          %{"arguments" => [3,
            2],
            "expected" => 5}],
        count: nil,
        creator_id: nil,
        description_en: "testsum",
        description_ru: "проверка суммы",
        disabled: false,
        examples: "asfd",
        id: 3327,
        input_signature: [%{"argument-name" => "a",
          "type" => %{"name" => "integer"}},
          %{"argument-name" => "b",

            "type" => %{"name" => "integer"}}],
        inserted_at: ~N[2021-12-07 13:00:23],
        level: "easy",
        name: "3A03",
        origin: "user",
        output_signature: %{"type" => %{"name"=> "integer"}},
        state: "active",
        tags: [],
        updated_at: ~N[2021-12-07 13:00:23],
        visibility: "public"}}]
  end
end




[ %{__struct__: Codebattle.Game.Player,
  achievements: [],
  check_result: %Codebattle.CodeCheck.CheckResult{asserts: [],
    asserts_count: 0,
    output: "",
    result: "{\"status\": \"info\"}",
    status: "initial",
    success_count: 0},
  creator: true,
  editor_lang: "js",
  editor_text: "const _ = require(\"lodash\");\nconst R = require(\"rambda\");\n\nconst solution = (a, b) => {\n\treturn 0;\n};\n\nmodule.exports = solution;",
  id: 4207778,
  is_bot: false,
  lang: "js",
  name: "User 0",
  rank: 5432,
  rating: 991,
  rating_diff: -10,
  result: "gave_up",
  task: %Codebattle.Task{__meta__:  "tasks", asserts: [%{"arguments" => [1,
    1],
    "expected" => 2},
    %{"arguments" => [2,
      1],
      "expected" => 3},
    %{"arguments" => [3,
      2],
      "expected" => 5}],
    count: nil,

    creator_id: nil,
    description_en: "test sum",
    description_ru: "проверка суммы",
    disabled: false,
    examples: "asfd",
    id: 3327,
    input_signature: [%{"argument-name" => "a",
      "type" => %{"name" => "integer"}},
      %{"argument-name" => "b",
        "type" => %{"name" => "integer"}}],
    inserted_at: ~N[2021-12-07 13:00:23],
    level: "easy",
    name: "3A03",
    origin: "user",
    output_signature: %{"type" => %{"name" => "integer"}},
    state: "active",
    tags: [],
    updated_at:~N[2021-12-07 13:00:23],
    visibility: "public"}},
    %{__struct__: Codebattle.Game.Player,
      achievements: [],
      check_result: %Codebattle.CodeCheck.CheckResult{asserts: [],
        asserts_count: 0,
        output: "",
        result: "{\"status\": \"info\"}",
        status: "initial",
        success_count: 0},
      creator: false,
      editor_lang: "js", editor_text: "const _ = require(\"lodash\");\nconst R = require(\"rambda\");\n\nconst solution = (a,
        b) => {\n\treturn 0;\n};\n\nmodule.exports = solution;",




      id: 7881260,
      is_bot: false,
      lang: "js",
      name: "User 2",
      rank: 5432,
      rating: 1002,
      rating_diff: 0,

      result: "won",
      task: %Codebattle.Task{__meta__: "tasks",
        asserts: [%{"arguments" => [1,
          1],
          "expected" => 2},
          %{"arguments" => [2,
            1],
            "expected" => 3},
          %{"arguments" => [3,
            2],
            "expected" => 5}],
        count: nil,
        creator_id: nil,
        description_en: "test sum",
        description_ru: "проверка суммы",
        disabled: false,
        examples: "asfd",

        id: 3327,
        input_signature: [%{"argument-name" => "a",
          "type" => %{"name" => "integer"}},
          %{"argument-name" => "b",
            "type" => %{"name" => "integer"}}],
        inserted_at: ~N[2021-12-07 13:00:23],
        level: "easy",
        name: "3A03",
        origin: "user",
        output_signature: %{"type" => %{"name" => "integer"}}, state: "active",

        tags: [],

        updated_at: ~N[2021-12-07 13:00:23],
        visibility: "public"}}],


