FROM elixir:1.19.1-otp-28-alpine

# Install Elixir dependencies as root
RUN mix local.hex --force \
  && mix local.rebar --force \
  && mix archive.install hex phx_new --force

# Install system dependencies
RUN apk add --no-cache \
  inotify-tools \
  curl \
  vim \
  chromium \
  postgresql-client \
  build-base \
  git

# Install Node.js and pnpm
RUN apk add --no-cache nodejs npm \
  && npm install --global pnpm

# Install Podman for local development
RUN apk add --no-cache podman

# Add non-root user
RUN adduser -D developer

# Copy Hex and other Mix archives from root to developer
RUN cp -R /root/.mix /home/developer/ && chown -R developer:developer /home/developer/.mix

# Switch to non-root user
USER developer

# Set working directory
WORKDIR /app

ARG GIT_HASH
ENV APP_VERSION=$GIT_HASH
ENV NODE_OPTIONS="--max-old-space-size=4096"
