FROM elixir:1.19.1-otp-28-alpine
ENV DOCKER_CHANNEL stable
ENV DOCKER_VERSION 20.10.9

# Install Elixir dependencies as root
RUN mix local.hex --force \
  && mix local.rebar --force \
  && mix archive.install hex phx_new --force

# Install system dependencies
RUN apk add --no-cache \
  inotify-tools \
  curl \
  vim \
  chromium \
  postgresql-client \
  build-base \
  git

# Install Node.js and Yarn
RUN apk add --no-cache nodejs npm \
  && npm install --global yarn@1.22.10

# Install Docker for local development
RUN curl -fsSL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

# Add non-root user
RUN adduser -D developer

# Copy Hex and other Mix archives from root to developer
RUN cp -R /root/.mix /home/developer/ && chown -R developer:developer /home/developer/.mix

# Switch to non-root user
USER developer

# Set working directory
WORKDIR /app

ARG GIT_HASH
ENV APP_VERSION=$GIT_HASH
