FROM ubuntu:18.04

WORKDIR /app

RUN apt-get update \
  && apt-get install -y inotify-tools vim curl postgresql-client make

ENV DOCKER_CHANNEL edge
ENV DOCKER_VERSION 19.03.5
RUN curl -fsSL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

COPY _build/prod/rel/codebattle .
COPY Makefile Makefile
CMD exec /app/bin/codebattle start
