use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.

config :codebattle, CodebattleWeb.Endpoint,
  http: [port: System.get_env("CODEBATTLE_PORT")],
  url: [scheme: "http", host: "codebattle.hexlet.io", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Mix.Project.config()[:version]

config :phoenix, :serve_endpoints, true

config :codebattle, Codebattle.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: System.get_env("CODEBATTLE_DB_NAME"),
  ssl: true,
  port: System.get_env("CODEBATTLE_DB_PORT"),
  username: System.get_env("CODEBATTLE_DB_USERNAME"),
  password: System.get_env("CODEBATTLE_DB_PASSWORD"),
  database: System.get_env("CODEBATTLE_DB_NAME"),
  hostname: System.get_env("CODEBATTLE_DB_HOSTNAME"),
  pool_size: 15

config :logger, backends: [{LoggerFileBackend, :info}, {LoggerFileBackend, :error}]

config :logger, :error,
  path: "/var/log/codebattle/error.log",
  level: :error

config :logger, :info,
  path: "/var/log/codebattle/info.log",
  level: :info

config :codebattle, Codebattle.Bot, timeout: 1000
