apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - codebattle.hexlet.io
    secretName: certificate-frontend
  rules:
  - host: "codebattle.hexlet.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "{{ .Release.Name }}-frontend"
            port:
              number: 8080
# spec:
  # tls:
  # - hosts:
  #   - codebattle.hexlet.io
  #   secretName: certificate-frontend
  # rules:
  # - host: codebattle.hexlet.io
  #   http:
  #     paths:
  #     - backend:
  #         service:
  #           name: "{{ .Release.Name }}-frontend"
  #           port: 8080
