---
- hosts: all

  tasks:
    - name: pull dockers for tasks
      shell: "docker pull {{ item }}"
      with_items:
        - "codebattle/ruby:2.6.0"
        - "codebattle/js:11.6.0"
        - "codebattle/ts:3.5.2"
        - "codebattle/golang:1.12.6"
        - "codebattle/cpp:17"
        - "codebattle/elixir:1.7.3"
        - "codebattle/python:3.7.2"
        - "codebattle/php:7.3.0"
        - "codebattle/haskell:8.4.3"
        - "codebattle/clojure:1.10.0"

    - name: prune docker images
      shell: docker rmi -f $(docker images | grep "<none>" | awk '{print $3}')
