---
root: true

plugins:
  - react
  - jsx-a11y
  - jest
  - react-hooks
env:
  node: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  react/prop-types: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
  import/order:
  - 2
  - newlines-between: always
    alphabetize:
      order: asc
      caseInsensitive: true
    groups:
      - builtin
      - external
      - internal
      - parent
      - sibling
      - index
    pathGroups:
      - pattern: react
        group: builtin
      - pattern: '@/**'
        group: internal
    pathGroupsExcludedImportTypes:
      - internal
  no-param-reassign: 0
  arrow-parens:
    - 2
    - "as-needed"
  react/jsx-props-no-spreading: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  jest/no-disabled-tests: "warn"
  jest/no-focused-tests: "error"
  jest/no-identical-title: "error"
  jest/prefer-to-have-length: "warn"
  jest/valid-expect: "error"
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  template-curly-spacing: "off"
  indent: "off"
  max-len: ["error", 140, 2]
  jsx-a11y/label-has-associated-control:
    - 2
    - assert: "either"
