---
root: true

plugins:
  - react
  - jsx-a11y
  - jest
  - react-hooks
  - sort-destructure-keys
env:
  node: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb"
  - "plugin:jest/recommended"
  - "plugin:prettier/recommended"

rules:
  no-console: 0
  react/prop-types: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
  import/order:
  - 2
  - newlines-between: always
    alphabetize:
      order: asc
      caseInsensitive: true
    groups:
      - builtin
      - external
      - internal
      - parent
      - sibling
      - index
    pathGroups:
      - pattern: react
        group: builtin
      - pattern: '@/**'
        group: internal
    pathGroupsExcludedImportTypes:
      - internal
  import/extensions:
    - error
    - js: never
      jsx: never
  no-param-reassign: 0
  arrow-parens:
    - 2
    - "always"
  react/jsx-props-no-spreading: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  react/function-component-definition: "off"
  react/jsx-sort-props:
    - 1
    - callbacksLast: true
      shorthandFirst: true
      shorthandLast: false
      ignoreCase: false
      noSortAlphabetically: false
      reservedFirst: true
      multiline: last
  react/no-unstable-nested-components:
    - warn
    - allowAsProps: true
  class-methods-use-this: "off"
  jest/no-disabled-tests: "warn"
  jest/no-focused-tests: "error"
  jest/no-identical-title: "error"
  jest/prefer-to-have-length: "warn"
  jest/valid-expect: "error"
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  template-curly-spacing: "off"
  indent: "off"
  max-len: ["error", 140, 2]
  sort-destructure-keys/sort-destructure-keys:
    - 1
    - caseSensitive: false
