test:
	g++ -o checker ./check/checker.cpp ./check/solution.cpp -lm && ./checker

test-example:
	g++ -o checker checker_example.cpp && ./checker

test-compile:
	g++ -c ./check/solution.cpp

test-example-compile:
	g++ -c solution_example.cpp

.PHONY: test
